"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-01 22:22:28.640980
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("query", sa.JSON(), nullable=False),
        sa.Column("found", sa.Integer(), nullable=False),
        sa.Column("new", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("http_stats", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_states",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_result_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "tenders",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("national_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("title_normalized", sa.Text(), nullable=True),
        sa.Column("contracting_authority", sa.Text(), nullable=True),
        sa.Column("authority_normalized", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("cpv_codes", sa.JSON(), nullable=False),
        sa.Column("notice_type", sa.String(length=128), nullable=True),
        sa.Column("procedure_type", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_value", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("primary_tender_id", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_decision", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["primary_tender_id"],
            ["tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenders_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenders_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenders_is_primary"), ["is_primary"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenders_national_id"), ["national_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tenders_primary_tender_id"), ["primary_tender_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenders_publication_date"), ["publication_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tenders_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenders_source_id"), ["source_id"], unique=False)
        batch_op.create_index("ix_tenders_source_source_id", ["source", "source_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_tenders_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tenders_submission_deadline"), ["submission_deadline"], unique=False
        )

    op.create_table(
        "tender_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("match_reason", sa.String(length=128), nullable=True),
        sa.Column("match_confidence", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tender_aliases", schema=None) as batch_op:
        batch_op.create_index("ix_alias_source_source_id", ["source", "source_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_tender_aliases_tender_id"), ["tender_id"], unique=False
        )

    op.create_table(
        "tender_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tender_changes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tender_changes_tender_id"), ["tender_id"], unique=False
        )

    op.create_table(
        "tender_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=128), nullable=True),
        sa.Column("access", sa.String(length=32), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tender_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tender_documents_tender_id"), ["tender_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tender_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tender_documents_tender_id"))

    op.drop_table("tender_documents")
    with op.batch_alter_table("tender_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tender_changes_tender_id"))

    op.drop_table("tender_changes")
    with op.batch_alter_table("tender_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tender_aliases_tender_id"))
        batch_op.drop_index("ix_alias_source_source_id")

    op.drop_table("tender_aliases")
    with op.batch_alter_table("tenders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenders_submission_deadline"))
        batch_op.drop_index(batch_op.f("ix_tenders_status"))
        batch_op.drop_index("ix_tenders_source_source_id")
        batch_op.drop_index(batch_op.f("ix_tenders_source_id"))
        batch_op.drop_index(batch_op.f("ix_tenders_source"))
        batch_op.drop_index(batch_op.f("ix_tenders_publication_date"))
        batch_op.drop_index(batch_op.f("ix_tenders_primary_tender_id"))
        batch_op.drop_index(batch_op.f("ix_tenders_national_id"))
        batch_op.drop_index(batch_op.f("ix_tenders_is_primary"))
        batch_op.drop_index(batch_op.f("ix_tenders_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_tenders_content_hash"))

    op.drop_table("tenders")
    op.drop_table("source_states")
    op.drop_table("ingest_runs")
    # ### end Alembic commands ###
