"""document extracts

Revision ID: 0003_document_extracts
Revises: 0002_blocking_key
Create Date: 2026-09-02 02:33:28.968894
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0003_document_extracts"
down_revision = "0002_blocking_key"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_extracts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("extractor", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("table_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("tables", sa.JSON(), nullable=False),
        sa.Column("doc_metadata", sa.JSON(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("ocr_used", sa.Boolean(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["tender_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_extracts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_extracts_checksum_sha256"), ["checksum_sha256"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_extracts_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_document_extracts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_document_extracts_tender_id"), ["tender_id"], unique=False
        )

    with op.batch_alter_table("tender_documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("size_bytes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tender_documents", schema=None) as batch_op:
        batch_op.drop_column("size_bytes")

    with op.batch_alter_table("document_extracts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_extracts_tender_id"))
        batch_op.drop_index(batch_op.f("ix_document_extracts_status"))
        batch_op.drop_index(batch_op.f("ix_document_extracts_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_extracts_checksum_sha256"))

    op.drop_table("document_extracts")
    # ### end Alembic commands ###
