"""risk analyses

Revision ID: 0004_risk_analyses
Revises: 0003_document_extracts
Create Date: 2026-09-02 02:51:04.004270
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0004_risk_analyses"
down_revision = "0003_document_extracts"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_analyses",
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("documents_analyzed", sa.Integer(), nullable=False),
        sa.Column("documents_unreadable", sa.Integer(), nullable=False),
        sa.Column("characters_analyzed", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tender_id"),
    )
    with op.batch_alter_table("risk_analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_analyses_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_analyses_score"), ["score"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_analyses_score"))
        batch_op.drop_index(batch_op.f("ix_risk_analyses_level"))

    op.drop_table("risk_analyses")
    # ### end Alembic commands ###
