"""tender items

Revision ID: 0005_tender_items
Revises: 0004_risk_analyses
Create Date: 2026-09-02 07:50:21.718348
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0005_tender_items"
down_revision = "0004_risk_analyses"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_extractions",
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("priceable_count", sa.Integer(), nullable=False),
        sa.Column("average_confidence", sa.Integer(), nullable=False),
        sa.Column("documents_scanned", sa.Integer(), nullable=False),
        sa.Column("tables_scanned", sa.Integer(), nullable=False),
        sa.Column("tables_used", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tender_id"),
    )
    with op.batch_alter_table("item_extractions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_item_extractions_item_count"), ["item_count"], unique=False
        )

    op.create_table(
        "tender_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=64), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("quantity_estimated", sa.Boolean(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("unit_original", sa.String(length=64), nullable=True),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("model_number", sa.String(length=255), nullable=True),
        sa.Column("article_number", sa.String(length=128), nullable=True),
        sa.Column("specifications", sa.JSON(), nullable=False),
        sa.Column("brand_locked", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("match_confidence", sa.Integer(), nullable=True),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("document", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tender_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tender_items_brand_locked"), ["brand_locked"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tender_items_confidence"), ["confidence"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tender_items_tender_id"), ["tender_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tender_items_unit"), ["unit"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tender_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tender_items_unit"))
        batch_op.drop_index(batch_op.f("ix_tender_items_tender_id"))
        batch_op.drop_index(batch_op.f("ix_tender_items_confidence"))
        batch_op.drop_index(batch_op.f("ix_tender_items_brand_locked"))

    op.drop_table("tender_items")
    with op.batch_alter_table("item_extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_extractions_item_count"))

    op.drop_table("item_extractions")
    # ### end Alembic commands ###
