"""price research

Revision ID: 0006_price_quotes
Revises: 0005_tender_items
Create Date: 2026-09-05 01:46:17.908519
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0006_price_quotes"
down_revision = "0005_tender_items"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_research",
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("usable_count", sa.Integer(), nullable=False),
        sa.Column("coverage_percent", sa.Integer(), nullable=False),
        sa.Column("sources_used", sa.JSON(), nullable=False),
        sa.Column("sources_failed", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("researched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tender_id"),
    )
    with op.batch_alter_table("price_research", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_price_research_coverage_percent"), ["coverage_percent"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_research_usable_count"), ["usable_count"], unique=False
        )

    op.create_table(
        "price_quotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("supplier", sa.String(length=255), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("model_number", sa.String(length=255), nullable=True),
        sa.Column("article_number", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("basis", sa.String(length=16), nullable=False),
        sa.Column("vat_rate", sa.Float(), nullable=True),
        sa.Column("net_amount", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("tiers", sa.JSON(), nullable=False),
        sa.Column("shipping_cost", sa.Float(), nullable=True),
        sa.Column("shipping_included", sa.Boolean(), nullable=True),
        sa.Column("min_order_quantity", sa.Float(), nullable=True),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("match_confidence", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("concerns", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("document", sa.Text(), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["tender_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_quotes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_price_quotes_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_price_quotes_match_confidence"), ["match_confidence"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_price_quotes_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_price_quotes_supplier"), ["supplier"], unique=False)
        batch_op.create_index(batch_op.f("ix_price_quotes_tender_id"), ["tender_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_quotes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_quotes_tender_id"))
        batch_op.drop_index(batch_op.f("ix_price_quotes_supplier"))
        batch_op.drop_index(batch_op.f("ix_price_quotes_source"))
        batch_op.drop_index(batch_op.f("ix_price_quotes_match_confidence"))
        batch_op.drop_index(batch_op.f("ix_price_quotes_item_id"))

    op.drop_table("price_quotes")
    with op.batch_alter_table("price_research", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_research_usable_count"))
        batch_op.drop_index(batch_op.f("ix_price_research_coverage_percent"))

    op.drop_table("price_research")
    # ### end Alembic commands ###
